version: '3.8'

services:
  mock-register:
    container_name: mock-register
    image: consumerdatastandardsaustralia/mock-register:0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mssql:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:7006/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50      
    depends_on:
      mssql:
        condition: service_healthy
  
  mssql:
    container_name: mssql
    image: consumerdatastandardsaustralia/energy-sql-data
    #image: 'mcr.microsoft.com/mssql/server:2019-latest'
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mock-register:host-gateway"
    ports:
      - "1433:1433"
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 10s
      interval: 10s
      retries: 10 




  
